os: linux

dist: xenial

matrix:
  include:
    - language: ruby
      cache: bundler
      rvm: 
        - 2.4.5
        - 2.5.4
        - 2.6.2
    - language: shell
      script: echo "Testing"

script:
  - ruby -v

services:
  - docker